version: '3.5'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - redis
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - mongo:/data/db

  redis:
    image: redis

volumes:
  mongo: